package com.checkers.server;

import com.checkers.server.controller.GameRepository;
import com.checkers.server.controller.UserRepository;
import com.checkers.server.model.Game;
import com.checkers.server.model.User;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.List;

@SpringBootTest
class CheckersApplicationTests {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
	private GameRepository gameRepository;

	@Test
	void contextLoads() {
		User u1 = new User("www", "123", "Marina");
		User u2 = new User("qqq", "123", "Max");
		User u3 = new User("rrr", "123", "Miri");
		userRepository.save(u1);
		userRepository.save(u2);
		userRepository.save(u3);

		Game g1 = new Game(u1,u2);
		Game g2 = new Game(u1,u3);
		Game g3 = new Game(u2,u1);
		Game g4 = new Game(u3,u2);
		Game g5 = new Game(u3,u1);

		gameRepository.save(g1);
		gameRepository.save(g2);
		gameRepository.save(g3);
		gameRepository.save(g4);
		gameRepository.save(g5);


		List<Game> games = gameRepository.findAllGamesForUser(u1);


	}

}
